### PR TITLE
Refactor and clean code + Add docstring

### PR DESCRIPTION
**Pull request by StrixzIV**
I move all Jarvis interaction and the voice utilities into a new modules so it would be easier to develop and expand your code

### CODE REVIEW

**Comment by StrixzIV** [comment]
Please make sure to test first before merging. Hope you like it!

**Review by subhadip-saha-05 — APPROVED** [review]

**Comment by subhadip-saha-05** [comment]
Good job

**Comment by subhadip-saha-05** [comment]
Please Update the readme file too...
with installation process and 'how to run'

**Comment by StrixzIV** [comment]
Ok, I'm finish rewriting it.

Please take a look at #16 

And could you tell me why you revert my pull request so I can fix the problem

**Pull request merged**
