### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by laxminaryana**
add core.check-connection()
import sys
import threading
import tkinter

### CODE REVIEW

**Comment by subhadip-saha-05** [comment]
image

**Comment by subhadip-saha-05** [comment]
pls resolve the conflits, otherwise I can't merge it

**Review by 072arushi — CHANGES_REQUESTED** [review]
Not a considerable contribution

**Review by subhadip-saha-05 — CHANGES_REQUESTED** [review]
This branch has some conflicts, please do the necessary changes

**Review by 072arushi — APPROVED** [review]

**Pull request closed without merging**
