### PR TITLE
Weather

### PR DESCRIPTION
**Pull request by PK284**
As assigned I have added a new feature to check the weather of any city city using gogle search.

### CODE REVIEW

**Comment by PK284** [comment]
@subhadip-saha-05 kindly check and merge

**Review by subhadip-saha-05 — COMMENTED** [review]
Please review and make changes to your code.

**Comment by subhadip-saha-05** [comment]
This Branch has conflicts that must be resolved

**Review by PK284 — COMMENTED** [review]
I have tried to remove the conflicts kindly check

**Comment by subhadip-saha-05** [comment]
image
Your code has some conflicts !! 
By the way, another one contributor already have added weather. You better work on another issue.

**Pull request closed without merging**
