### PR TITLE
Refactored code with addition of name

### PR DESCRIPTION
**Pull request by isha-73**
Along with Edited weather, meaning queries. Alarm is commented for now to prevent termination of program.

### CODE REVIEW

**Comment by yash240408** [comment]
@isha-73 This has branch conflict, resolve this to get this merged asap.

**Comment by isha-73** [comment]
@yash240408  please check now...

**Comment by subhadip-saha-05** [comment]
Please raise an issue, otherwise, I can't give you marks

**Comment by isha-73** [comment]
@subhadip-saha-05 Now you can check!

**Pull request merged**
